/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e2b05edb-2371-4442-8117-86be5e05c576",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_B0zLCmjRa",
    "aws_user_pools_web_client_id": "4cmcd360oee4n4lm6k353ef13p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://36pirw4w7zai7m3klvtd3x3n4i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
